[package]
name = "ethan/rolatro"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
cmdr = "evaera/cmdr@1.12.0"
bytenet = "ffrostflame/bytenet@0.4.6"
roact = "roblox/roact@1.4.4"