local Cards = {
    {name = "Ace", chips = 11, value = 14},
    {name = "Two", chips = 2, value = 2},
    {name = "Three", chips = 3, value = 3},
    {name = "Four", chips = 4, value = 4},
    {name = "Five", chips = 5, value = 5},
    {name = "Six", chips = 6, value = 6},
    {name = "Seven", chips = 7, value = 7},
    {name = "Eight", chips = 8, value = 8},
    {name = "Nine", chips = 9, value = 9},
    {name = "Ten", chips = 10, value = 10},
    {name = "Jack", chips = 10, value = 11},
    {name = "Queen", chips = 10, value = 12},
    {name = "King", chips = 10, value = 13}
}

return Cards